<template>
  <div class="trips-wrapper">
    <v-data-table
      :headers="headers"
      :items="dataList"
      :hide-default-footer="true"
      class="global-table fixed-header"
      fixed-header
      disable-pagination
    >
    </v-data-table>
  </div>
</template>

<script>
export default {
  data() {
    return {
      headers: [
        {
          text: "Trip Id",
          value: "tripId",
          align: "center",
        },
        {
          text: "Destinations",
          value: "destinations",
        },
        {
          text: "Trip Type",
          value: "tripType",
          align: "center",
        },
        {
          text: "Timeline",
          value: "timeline",
          align: "center",
        },
        {
          text: "Start Date",
          value: "startDate",
          align: "center",
        },
        {
          text: "End Date",
          value: "endDate",
          align: "center",
        },
        {
          text: "Members",
          value: "members",
          align: "center",
        },
        {
          text: "Feedback",
          value: "feedback",
        },
      ],
      dataList: [
        {
          tripId: "#US14253",
          destinations: "Maldives",
          tripType: "Solo",
          timeline: 3,
          startDate: "25 May, 2023",
          endDate: "27 May, 2023",
          members: "",
          feedback: "Had a really wonderful experience. Loved the...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14254",
          destinations: "Bali, Thailand",
          tripType: "Friends",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "A awesome trip and prepared a best itinerary for...",
        },
        {
          tripId: "#US14255",
          destinations: "France, Belgium, Italy",
          tripType: "Family",
          timeline: 6,
          startDate: "31 May, 2021",
          endDate: "05 Jun, 2021",
          members: "",
          feedback: "It's really awesome trip.",
        },
        {
          tripId: "#US14256",
          destinations: "India",
          tripType: "Group",
          timeline: 8,
          startDate: "21 Sep, 2022",
          endDate: "28 Sep, 2022",
          members: "",
          feedback: "Had a really wonderful experience. Loved the...",
        },
        {
          tripId: "#US14257",
          destinations: "China",
          tripType: "Official",
          timeline: 8,
          startDate: "25 May, 2023",
          endDate: "27 May, 20239",
          members: "",
          feedback: "It's really awesome trip.",
        },
      ],
    };
  },
};
</script>

<style scoped>

.trips-wrapper{
  overflow: auto;
}


</style>
